# Autogenerated wrapper script for SpineRuntimes_jll for aarch64-apple-darwin
export libspine

JLLWrappers.@generate_wrapper_header("SpineRuntimes")
JLLWrappers.@declare_library_product(libspine, "@rpath/libspine-c.dylib")
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_library_product(
        libspine,
        "lib/libspine-c.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
