# Autogenerated wrapper script for SpineRuntimes_jll for i686-linux-gnu
export libspine

JLLWrappers.@generate_wrapper_header("SpineRuntimes")
JLLWrappers.@declare_library_product(libspine, "libspine-c.so")
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_library_product(
        libspine,
        "lib/libspine-c.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
